version: "3"

services:

  app: 
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ilyasgaly/devops-for-programmers-project-74
    command: make test
    volumes:
      - "./app:/app"